### ISSUE TITLE
summaryLength 속성 값 관련

### ISSUE THREAD

**Issue by zeus6768** [jun23314/teamWebPage#8]
## As-is
`config.toml`  `summaryLength` 속성 기본값입니다. 

```
# number of words of summarized post content (default 70)
summaryLength = 70
```
### 결과
<img width="640" alt="Screenshot 2023-05-24 at 4 07 10 PM" src="https://github.com/jun23314/teamWebPage/assets/81848498/463c8baa-046c-4a7e-8c4a-af940311d4ca">

## To-be
50으로 수정하면 다음과 같습니다. 

```
# number of words of summarized post content (default 70)
summaryLength = 50
```
### 결과
<img width="640" alt="Screenshot 2023-05-24 at 4 16 41 PM" src="https://github.com/jun23314/teamWebPage/assets/81848498/099a8e3a-c62a-4d6a-91e6-87f4a87b3527">

## 결론
- 한글 내용 작성 시 모양이 일그러지므로 50으로 변경하면 좋을 것 같습니다. 따로 의견 없을 경우 제 커밋에 반영하겠습니다.

**Comment by jun23314** [comment]
넵 알겠습니다!
