### ISSUE TITLE
date_format 관련

### ISSUE THREAD

**Issue by zeus6768** [jun23314/teamWebPage#9]
`Config.toml`의 `date_format` 속성을 `"Jan 02, 2006"`으로 변경합니다. 

다른 값일 경우 오류가 납니다. 

출처: https://stackoverflow.com/questions/56646943/how-to-render-correct-datetime-in-hugo-post

다른 의견 없을 경우 제 커밋에 적용해서 merge 할 때 반영되게 하겠습니다 ~

**Comment by jun23314** [comment]
넵 알겠습니다~
